import {
  Special_Gothic
} from "next/font/google";
import "../globals.css";
import {Providers} from "././../Providers";
import Header from "./H&F/Header";
import Curtain from "../(dashboardlayout)/about/Componenets/Shared/Curtain";

const geistSans = Special_Gothic
  ({
    weight: ["400", "500", "600", "700"]
  });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
       <div className="font-gothic">

         <Providers>
          
         
          {children}
        </Providers>

       </div>
      </body>
    </html>
  );
}
